# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-12 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('eno', models.IntegerField()),
                ('uid', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254, null=True)),
                ('phone_no', models.CharField(max_length=20)),
                ('phone_no_alt', models.CharField(max_length=20)),
                ('room_no', models.CharField(max_length=7)),
                ('bhawan', models.CharField(choices=[('GB', 'Govind Bhawan'), ('KB', 'Kasturba Bhawan'), ('RB', 'Rajiv Bhawan')], max_length=2)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
